let S=null,PRIVACY=localStorage.getItem('qg_privacy')==='1';
const $=id=>document.getElementById(id);
async function api(path,data=null){
  const o=data===null?{}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)};
  const r=await fetch(path,o);let j={};try{j=await r.json()}catch{}
  if(r.status===401){$('app').hidden=true;$('login').hidden=false;throw Error('unauthorized')}
  if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j;
}
function fmt(b){b=Number(b||0);for(const u of ['B','KB','MB','GB','TB']){if(b<1024)return b.toFixed(u==='B'?0:2)+' '+u;b/=1024}return b.toFixed(2)+' PB'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sensitive(v){return PRIVACY?'••••••':esc(v)}
function toast(html){modal(`<div>${html}</div>`)}
async function login(){try{await api('/api/login',{password:$('pw').value,totp:$('totp').value});$('login').hidden=true;$('app').hidden=false;await refreshAll()}catch(e){$('loginErr').textContent=e.message}}
async function refreshAll(){S=await api('/api/status');render()}
function togglePrivacy(){PRIVACY=!PRIVACY;localStorage.setItem('qg_privacy',PRIVACY?'1':'0');if(S)render()}
function render(){
 const b=S.bundle,total=Number(b.total_gb||0)*1024**3,used=Number(b.used_bytes||0),pct=total?Math.min(100,used/total*100):0;
 $('bundle').innerHTML=`<b>${fmt(used)} / ${Number(b.total_gb||0).toFixed(1)} GB</b><div class="progress"><i style="width:${pct}%"></i></div><small>${pct.toFixed(1)}% مستخدم</small>`;
 $('devCount').innerHTML=`<b>${S.devices.length}</b> جهاز<br><small>${S.devices.filter(d=>Date.now()/1000-d.last_seen<120).length} نشط حديثاً</small>`;
 $('networkMini').innerHTML=`WAN: <b>${esc(S.network.wan_interface)}</b><br>LAN: <b>${esc(S.network.lan_interface)}</b><br>Gateway: <b>${sensitive(S.network.lan_ip)}</b>`;
 $('netTitle').textContent=PRIVACY?'Privacy Mode':S.network.lan_ip;
 $('alertBadge').textContent=S.alerts.filter(a=>!a.seen).length;
 renderUsers();renderDevices();renderSettings();renderMac();renderAdmin();renderHistSelect();loadDnsRules();loadFirewall();
}
function modeName(m){return m==='auto'||m==='shared'?'Auto':m==='disabled'?'Disabled':'Fixed'}
function renderUsers(){
 const box=$('users');box.innerHTML='<h2>المستخدمون</h2>';
 for(const u of S.users){
  const q=Number(u.effective_quota_gb||0),used=Number(u.usage_bytes||0),pct=q?Math.min(100,used/(q*1024**3)*100):0,devs=S.devices.filter(d=>d.user_id===u.id);
  box.innerHTML+=`<div class="card user"><div class="row"><h3>${esc(u.name)}</h3><span class="pill">${modeName(u.quota_mode)}</span>${u.exempt?'<span class="pill ok">Unlimited</span>':''}${!u.enabled||u.quota_mode==='disabled'?'<span class="pill bad">Disabled</span>':''}</div><div>${fmt(used)} / ${q.toFixed(2)} GB</div><div class="progress"><i style="width:${pct}%"></i></div><small>${devs.length} أجهزة • ${u.speed_down_kbit||0}↓ / ${u.speed_up_kbit||0}↑ kbit</small><div class="toolbar"><button onclick="editUser(${u.id})">تعديل</button><button class="ghost" onclick="topup(${u.id})">Top-up</button><button class="danger" onclick="delUser(${u.id})">حذف</button></div><div>${devs.map(deviceMini).join('')}</div></div>`;
 }
}
function deviceMini(d){return `<div class="row device-line"><b>${esc(d.name)}</b><span class="muted">${sensitive(d.ip)}</span><span class="pill sensitive">${sensitive(d.mac)}</span><button class="ghost" onclick="editDevice(${d.id})">إدارة</button></div>`}
function renderDevices(){
 const un=S.devices.filter(d=>!d.user_id);$('devices').innerHTML=un.map(d=>`<div class="card device"><h3>${esc(d.name)}</h3><div>${sensitive(d.ip)}</div><small class="sensitive">${sensitive(d.mac)} ${esc(d.manufacturer||'')}</small><div class="row"><span class="pill ${d.enabled?'ok':'bad'}">${d.enabled?'Enabled':'Disabled'}</span>${d.is_guest?'<span class="pill">Guest</span>':''}${d.blocked_manual?'<span class="pill bad">Manual Block</span>':''}</div><button onclick="editDevice(${d.id})">إدارة</button></div>`).join('')||'<div class="muted">لا توجد أجهزة غير مخصصة.</div>'
}
function renderSettings(){const n=S.network,b=S.bundle,w=S.wifi||{},d=S.dns||{};
 $('bundleGb').value=b.total_gb;$('resetDay').value=b.reset_day||1;$('bundleType').value=b.bundle_type||'renew_day';$('autoReset').checked=b.auto_reset!==false;
 $('lineDown').value=n.line_down_mbit;$('lineUp').value=n.line_up_mbit;$('speedLimits').checked=true;$('stopNew').checked=!!n.stop_new_connections;$('declineRandom').checked=!!n.decline_random_macs;$('vpnShare').checked=!!n.vpn_share;$('vpnAuto').checked=n.vpn_auto_detect!==false;$('vpnIface').value=n.vpn_interface||'tun0';
 $('wifiSsid').value=w.ssid||'';$('wifiPassword').value='';$('wifiHidden').checked=!!w.hidden;$('wifiChannel').value=String(w.channel||1);$('wifiState').textContent=w.hidden?'الشبكة مخفية':'الشبكة ظاهرة';$('wifiPasswordState').textContent=w.password_set?'كلمة المرور محفوظة':'كلمة المرور غير مضبوطة';
 $('familyMode').checked=!!d.family_mode;$('dnsRetention').value=d.history_days||7;const p=d.presets||{};$('presetAds').checked=!!p.ads_tracking;$('presetSocial').checked=!!p.social;$('presetStreaming').checked=!!p.streaming;$('presetGambling').checked=!!p.gambling;$('presetAdult').checked=!!p.adult;
 fetch('/api/settings').then(r=>r.json()).then(c=>{if(c.guest){$('guestEnabled').checked=!!c.guest.enabled;$('guestQuota').value=c.guest.quota_gb;$('guestDown').value=c.guest.speed_down_kbit;$('guestUp').value=c.guest.speed_up_kbit}if(c.features)$('speedLimits').checked=!!c.features.speed_limits}).catch(()=>{})
}
async function saveNetwork(){try{await api('/api/settings',{bundle:{total_gb:+$('bundleGb').value,reset_day:+$('resetDay').value,bundle_type:$('bundleType').value,auto_reset:$('autoReset').checked},network:{line_down_mbit:+$('lineDown').value,line_up_mbit:+$('lineUp').value,stop_new_connections:$('stopNew').checked,decline_random_macs:$('declineRandom').checked,vpn_share:$('vpnShare').checked,vpn_auto_detect:$('vpnAuto').checked,vpn_interface:$('vpnIface').value},features:{speed_limits:$('speedLimits').checked},guest:{enabled:$('guestEnabled').checked,quota_gb:+$('guestQuota').value,speed_down_kbit:+$('guestDown').value,speed_up_kbit:+$('guestUp').value}});await refreshAll();toast('<h3>تم الحفظ</h3><p>تم تطبيق إعدادات الشبكة بدون Reboot.</p>')}catch(e){toast(`<h3>خطأ</h3><p class="bad">${esc(e.message)}</p>`)}}
async function saveWifi(){const ssid=$('wifiSsid').value.trim(),password=$('wifiPassword').value,hidden=$('wifiHidden').checked,channel=+$('wifiChannel').value;if(!ssid)return toast('<h3>خطأ</h3><p class="bad">SSID لا يمكن أن يكون فارغاً.</p>');const n=new TextEncoder().encode(password).length;if(password&&(n<8||n>63))return toast('<h3>خطأ</h3><p class="bad">كلمة المرور يجب أن تكون 8-63 بايت.</p>');if(!confirm('سيتم إعادة تشغيل نقطة Wi-Fi وقد ينقطع اتصال الأجهزة لثوانٍ. متابعة؟'))return;try{const j=await api('/api/wifi',{ssid,password,hidden,channel});$('wifiPassword').value='';if(S&&j.wifi)S.wifi=j.wifi;toast(`<h3>تم الحفظ</h3><p>SSID: ${esc(ssid)} — ${hidden?'مخفية':'ظاهرة'}.</p>`)}catch(e){toast(`<h3>فشل Wi-Fi</h3><p class="bad">${esc(e.message)}</p>`)}}
async function rescan(){try{await api('/api/network/rescan',{});await refreshAll()}catch(e){alert(e.message)}}
function showAddUser(){modal(`<h2>مستخدم جديد</h2><label>الاسم<input id="mName"></label><label>نوع الحصة<select id="mMode"><option value="fixed">Fixed</option><option value="auto">Auto</option><option value="disabled">Disabled</option></select></label><label>Quota GB<input id="mQuota" type="number" step="0.1" value="5"></label><label>Download kbit<input id="mDown" type="number" value="0"></label><label>Upload kbit<input id="mUp" type="number" value="0"></label><button onclick="addUser()">إنشاء</button>`)}
async function addUser(){await api('/api/users',{name:$('mName').value,quota_mode:$('mMode').value,quota_gb:+$('mQuota').value,speed_down_kbit:+$('mDown').value,speed_up_kbit:+$('mUp').value});closeModal();refreshAll()}
function editUser(id){const u=S.users.find(x=>x.id===id),m=u.quota_mode==='shared'?'auto':u.quota_mode;modal(`<h2>تعديل ${esc(u.name)}</h2><label>الاسم<input id="mName" value="${esc(u.name)}"></label><label>الحصة<select id="mMode"><option value="fixed" ${m==='fixed'?'selected':''}>Fixed</option><option value="auto" ${m==='auto'?'selected':''}>Auto</option><option value="disabled" ${m==='disabled'?'selected':''}>Disabled</option></select></label><label>Quota<input id="mQuota" type="number" step="0.1" value="${u.quota_gb}"></label><label>Down kbit<input id="mDown" type="number" value="${u.speed_down_kbit}"></label><label>Up kbit<input id="mUp" type="number" value="${u.speed_up_kbit}"></label><label>Custom DNS<input id="mDns" value="${esc(u.dns_server||'')}"></label><label>History days<input id="mHist" type="number" min="1" max="90" value="${u.history_days||7}"></label><label><input id="mEx" type="checkbox" ${u.exempt?'checked':''}> Unlimited / Exempt</label><label><input id="mEn" type="checkbox" ${u.enabled?'checked':''}> Enabled</label><button onclick="saveUser(${id})">حفظ</button>`)}
async function saveUser(id){await api('/api/user/update',{id,name:$('mName').value,quota_mode:$('mMode').value,quota_gb:+$('mQuota').value,speed_down_kbit:+$('mDown').value,speed_up_kbit:+$('mUp').value,dns_server:$('mDns').value,history_days:+$('mHist').value,exempt:$('mEx').checked?1:0,enabled:$('mEn').checked?1:0});closeModal();refreshAll()}
async function topup(id){const gb=prompt('GB إضافية:','1');if(gb!==null){await api('/api/user/topup',{id,gb:+gb});refreshAll()}}
async function delUser(id){if(confirm('حذف المستخدم؟')){await api('/api/user/delete',{id});refreshAll()}}
function editDevice(id){const d=S.devices.find(x=>x.id===id),opts='<option value="">بدون مستخدم</option>'+S.users.map(u=>`<option value="${u.id}" ${u.id===d.user_id?'selected':''}>${esc(u.name)}</option>`).join('');modal(`<h2>الجهاز</h2><label>الاسم<input id="dName" value="${esc(d.name)}"></label><div class="sensitive">${sensitive(d.ip)} • ${sensitive(d.mac)}</div><label>المستخدم<select id="dUser">${opts}</select></label><label><input id="dEn" type="checkbox" ${d.enabled?'checked':''}> Enabled</label><label><input id="dBlock" type="checkbox" ${d.blocked_manual?'checked':''}> Manual Block</label><label><input id="dEx" type="checkbox" ${d.exempt?'checked':''}> Quota Exempt</label><label>Down kbit<input id="dDown" type="number" value="${d.speed_down_kbit}"></label><label>Up kbit<input id="dUp" type="number" value="${d.speed_up_kbit}"></label><label>Custom DNS<input id="dDns" value="${esc(d.dns_server||'')}"></label><button onclick="saveDevice(${id})">حفظ</button> <button class="danger" onclick="delDevice(${id})">حذف + Deny</button>`)}
async function saveDevice(id){await api('/api/device/update',{id,name:$('dName').value,user_id:$('dUser').value?+$('dUser').value:null,enabled:$('dEn').checked?1:0,blocked_manual:$('dBlock').checked?1:0,exempt:$('dEx').checked?1:0,speed_down_kbit:+$('dDown').value,speed_up_kbit:+$('dUp').value,dns_server:$('dDns').value});closeModal();refreshAll()}
async function delDevice(id){if(confirm('سيتم حذف الجهاز وإضافته للـ Deny List.')){await api('/api/device/delete',{id});closeModal();refreshAll()}}
async function resetMonth(){if(confirm('تصفير استهلاك الدورة الحالية؟')){await api('/api/reset-month',{});refreshAll()}}
function renderMac(){$('macRules').innerHTML=S.mac_rules.map(r=>`<div class="row"><code class="sensitive">${sensitive(r.mac)}</code><span class="pill ${r.action==='blacklist'?'bad':'ok'}">${esc(r.action)}</span><span>${esc(r.note)}</span></div>`).join('')}
async function saveMacRule(){await api('/api/mac-rule',{mac:$('macRuleMac').value,action:$('macRuleAction').value,note:$('macRuleNote').value});refreshAll()}
async function saveDnsSettings(){try{const presets={ads_tracking:$('presetAds').checked,social:$('presetSocial').checked,streaming:$('presetStreaming').checked,gambling:$('presetGambling').checked,adult:$('presetAdult').checked};const j=await api('/api/dns/settings',{family_mode:$('familyMode').checked,history_days:+$('dnsRetention').value,presets});S.dns=j.dns;toast('<h3>تم حفظ DNS</h3>')}catch(e){alert(e.message)}}
async function loadDnsRules(){try{const j=await api('/api/dns/rules');$('dnsRules').innerHTML=j.rules.map(r=>`<div class="card row"><b>${esc(r.domain)}</b><span class="pill">${esc(r.scope_type)}:${r.scope_id}</span><span class="pill">${esc(r.action)}</span>${r.target?`<span>${esc(r.target)}</span>`:''}<button class="danger" onclick="delDns(${r.id})">حذف</button></div>`).join('')||'<div class="muted">لا توجد قواعد DNS.</div>'}catch{}}
async function addDnsRule(){await api('/api/dns/rule/add',{scope_type:$('dnsScope').value,scope_id:+$('dnsScopeId').value||0,domain:$('dnsDomain').value,action:$('dnsAction').value,target:$('dnsTarget').value});$('dnsDomain').value='';loadDnsRules()}
async function delDns(id){await api('/api/dns/rule/delete',{id});loadDnsRules()}
function renderHistSelect(){const v=$('histDevice').value;$('histDevice').innerHTML='<option value="0">كل الأجهزة</option>'+S.devices.map(d=>`<option value="${d.id}">${esc(d.name)} - ${PRIVACY?'hidden':esc(d.ip)}</option>`).join('');$('histDevice').value=v||'0'}
async function loadHistory(){const j=await api(`/api/dns/history?device_id=${+$('histDevice').value}&hours=${+$('histHours').value}`);$('topDomains').innerHTML=j.top.map(x=>`<div class="row"><b>${esc(x.domain)}</b><span class="pill">${x.hits}</span><button class="ghost" onclick="quickDns('${esc(x.domain)}','block')">Block</button></div>`).join('');$('dnsHistory').innerHTML=j.history.slice(0,150).map(x=>`<div class="history-line"><small>${new Date(x.ts*1000).toLocaleString()}</small> ${sensitive(x.client_ip)} ${x.user_name?'['+esc(x.user_name)+']':''} → <b>${esc(x.domain)}</b> <span class="pill">${esc(x.action)}</span> <button class="ghost tiny" onclick="quickDns('${esc(x.domain)}','block')">Block</button> <button class="ghost tiny" onclick="quickDns('${esc(x.domain)}','allow')">Allow</button></div>`).join('')}
async function quickDns(domain,action){await api('/api/dns/rule/add',{scope_type:'global',scope_id:0,domain,action});loadDnsRules()}
async function loadFirewall(){try{const j=await api('/api/firewall');$('dmz').value=j.dmz||'';$('firewallLists').innerHTML='<h3>Rules</h3>'+j.rules.map(r=>`<div class="card row"><b>${esc(r.name)}</b><span>${esc(r.src||'*')} → ${esc(r.dst||'*')}</span><span class="pill">${esc(r.proto)}:${esc(r.dport||'*')}</span><span class="pill ${r.enabled?'ok':'bad'}">${r.enabled?'On':'Off'}</span><button class="ghost" onclick='editFw(${JSON.stringify(r)})'>تعديل</button><button class="danger" onclick="delFw(${r.id})">حذف</button></div>`).join('')+'<h3>Port Forwards</h3>'+j.forwards.map(r=>`<div class="card row"><b>${esc(r.name)}</b><span>${esc(r.proto)} ${r.external_port} → ${sensitive(r.internal_ip)}:${r.internal_port}</span><span class="pill ${r.enabled?'ok':'bad'}">${r.enabled?'On':'Off'}</span><button class="ghost" onclick='editPf(${JSON.stringify(r)})'>تعديل</button><button class="danger" onclick="delPf(${r.id})">حذف</button></div>`).join('')}catch{}}
async function addFw(){await api('/api/firewall/rule/add',{name:$('fwName').value,src:$('fwSrc').value,dst:$('fwDst').value,proto:$('fwProto').value,dport:$('fwPort').value,action:$('fwAction').value});loadFirewall()}
function editFw(r){modal(`<h3>تعديل Firewall Rule</h3><label>Name<input id="efName" value="${esc(r.name)}"></label><label>Source<input id="efSrc" value="${esc(r.src)}"></label><label>Destination<input id="efDst" value="${esc(r.dst)}"></label><label>Protocol<select id="efProto"><option ${r.proto==='any'?'selected':''}>any</option><option ${r.proto==='tcp'?'selected':''}>tcp</option><option ${r.proto==='udp'?'selected':''}>udp</option></select></label><label>Port<input id="efPort" value="${esc(r.dport)}"></label><label>Action<select id="efAction"><option ${r.action==='accept'?'selected':''}>accept</option><option ${r.action==='drop'?'selected':''}>drop</option><option ${r.action==='reject'?'selected':''}>reject</option></select></label><label><input id="efEnabled" type="checkbox" ${r.enabled?'checked':''}> Enabled</label><button onclick="saveFw(${r.id})">حفظ</button>`)}
async function saveFw(id){await api('/api/firewall/rule/update',{id,name:$('efName').value,src:$('efSrc').value,dst:$('efDst').value,proto:$('efProto').value,dport:$('efPort').value,action:$('efAction').value,enabled:$('efEnabled').checked?1:0});closeModal();loadFirewall()}
async function delFw(id){await api('/api/firewall/rule/delete',{id});loadFirewall()}
async function addPf(){await api('/api/firewall/forward/add',{name:$('pfName').value,proto:$('pfProto').value,external_port:+$('pfExt').value,internal_ip:$('pfIP').value,internal_port:+$('pfInt').value});loadFirewall()}
function editPf(r){modal(`<h3>تعديل Port Forward</h3><label>Name<input id="epName" value="${esc(r.name)}"></label><label>Protocol<select id="epProto"><option ${r.proto==='tcp'?'selected':''}>tcp</option><option ${r.proto==='udp'?'selected':''}>udp</option></select></label><label>External<input id="epExt" type="number" value="${r.external_port}"></label><label>Internal IP<input id="epIP" value="${esc(r.internal_ip)}"></label><label>Internal Port<input id="epInt" type="number" value="${r.internal_port}"></label><label><input id="epEnabled" type="checkbox" ${r.enabled?'checked':''}> Enabled</label><button onclick="savePf(${r.id})">حفظ</button>`)}
async function savePf(id){await api('/api/firewall/forward/update',{id,name:$('epName').value,proto:$('epProto').value,external_port:+$('epExt').value,internal_ip:$('epIP').value,internal_port:+$('epInt').value,enabled:$('epEnabled').checked?1:0});closeModal();loadFirewall()}
async function delPf(id){await api('/api/firewall/forward/delete',{id});loadFirewall()}
async function setDmz(){await api('/api/firewall/dmz',{ip:$('dmz').value});loadFirewall()}
function renderAdmin(){$('sysInfo').textContent=JSON.stringify(S.system,null,2);$('alerts').innerHTML=S.alerts.map(a=>`<div><small>${new Date(a.ts*1000).toLocaleString()}</small> <b>${esc(a.kind)}</b> ${esc(a.message)}</div>`).join('');$('logs').innerHTML=S.events.map(e=>`<div><small>${new Date(e.ts*1000).toLocaleString()}</small> <span class="${e.level==='error'?'bad':''}">${esc(e.level)}</span> ${esc(e.message)}</div>`).join('')}
async function markAlerts(){await api('/api/alerts/seen',{});refreshAll()}
async function changePw(){try{await api('/api/password',{password:$('newPw').value});$('newPw').value='';toast('<h3>تم تغيير كلمة المرور</h3>')}catch(e){alert(e.message)}}
async function setup2fa(){try{await api('/api/2fa/setup',{});const q=await api('/api/2fa/qr');$('twoInfo').innerHTML=q.png?`<img class="qr" src="${q.png}" alt="2FA QR"><small>امسح QR ثم أدخل الكود للتأكيد.</small>`:'<small>تم إنشاء إعداد 2FA. أدخل الكود للتأكيد.</small>'}catch(e){alert(e.message)}}
async function enable2fa(){try{await api('/api/2fa/enable',{code:$('twoCode').value});toast('<h3>تم تفعيل 2FA</h3>')}catch(e){alert(e.message)}}
async function disable2fa(){await api('/api/2fa/disable',{});$('twoInfo').innerHTML='';toast('<h3>تم إلغاء 2FA</h3>')}
async function enableHttps(){const j=await api('/api/https/enable',{});alert('تم إنشاء الشهادة. أعد تشغيل الخدمة ثم استخدم HTTPS.')}
async function disableHttps(){await api('/api/https/disable',{});alert('تم تعطيل HTTPS في الإعداد. أعد تشغيل الخدمة.')}
async function checkUpdate(){try{const j=await api('/api/update/check',{});$('updateInfo').innerHTML=j.ok?`Current: <code>${esc((j.current_commit||'unknown').slice(0,12))}</code><br>Remote: <code>${esc((j.remote_commit||'').slice(0,12))}</code><br><span class="pill ${j.available?'warn':'ok'}">${j.available?'Update available':'Up to date'}</span>`:`<span class="bad">${esc(j.error)}</span>`}catch(e){$('updateInfo').textContent=e.message}}
async function installUpdate(){if(!confirm('سيتم تحديث كود QuotaGate وإعادة تشغيل الخدمة مع Rollback عند الفشل. متابعة؟'))return;try{await api('/api/update/install',{});toast('<h3>بدأ التحديث</h3><p>قد تنقطع لوحة التحكم مؤقتاً. انتظر حوالي 15 ثانية ثم أعد فتحها.</p>')}catch(e){alert(e.message)}}
async function loadDiagnostics(withPing=false){try{const j=await api('/api/diagnostics'+(withPing?'?ping=1':''));$('diagLinks').innerHTML=`WAN: <span class="pill ${j.wan.up?'ok':'bad'}">${j.wan.up?'UP':'DOWN'}</span><pre>${esc(j.wan.summary||'')}</pre>LAN: <span class="pill ${j.lan.up?'ok':'bad'}">${j.lan.up?'UP':'DOWN'}</span><pre>${esc(j.lan.summary||'')}</pre><div>VPN: ${esc((j.vpn_interfaces||[]).join(', ')||'none')}</div>`;const w=j.wifi||{};$('wifiStations').innerHTML=(w.stations||[]).map(s=>`<div class="card"><div class="row"><b class="sensitive">${sensitive(s.mac)}</b><span class="pill ${s.signal_quality==='excellent'||s.signal_quality==='good'?'ok':s.signal_quality==='poor'?'bad':'warn'}">${esc(s.signal_quality)}</span></div><div>Signal: <b>${s.signal??'-'} dBm</b> / avg ${s.signal_avg??'-'}</div><div>TX: <b>${s.tx_bitrate_mbps??'-'} Mbps</b> • RX: <b>${s.rx_bitrate_mbps??'-'} Mbps</b></div><div>Expected: ${s.expected_throughput_mbps??'-'} Mbps</div><div>Retries: ${s.tx_retries||0} (${((s.retry_ratio||0)*100).toFixed(1)}%) • Failed: ${s.tx_failed||0}</div><small>Inactive: ${s.inactive_time??'-'} ms • Connected: ${s.connected_time??'-'} s</small></div>`).join('')||'<div class="muted">لا توجد Stations متصلة.</div>';if(withPing){const gp=j.gateway_ping||{},ip=j.internet_ping||{};$('diagPing').innerHTML=`Gateway ${pingHtml(gp)}<hr>Internet ${pingHtml(ip)}`}}catch(e){$('diagLinks').innerHTML=`<span class="bad">${esc(e.message)}</span>`}}
function pingHtml(p){return p.ok?`<span class="pill ok">${p.loss_percent}% loss</span><div>min/avg/max: ${p.min_ms}/${p.avg_ms}/${p.max_ms} ms</div><div>jitter: ${p.jitter_ms} ms</div>`:`<span class="pill bad">${esc(p.error||'failed')}</span>`}
function modal(html){$('modalBody').innerHTML=html;$('modal').hidden=false}function closeModal(){$('modal').hidden=true}
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='history')loadHistory();if(b.dataset.tab==='diagnostics')loadDiagnostics(false);if(b.dataset.tab==='admin')checkUpdate()});
fetch('/api/status').then(r=>{if(r.ok){$('login').hidden=true;$('app').hidden=false;return r.json()}throw 0}).then(j=>{S=j;render()}).catch(()=>{});
